### ISSUE TITLE
Unable to update attribute

### ISSUE THREAD

**Issue by NagarajuKasa** [akeneo/pim-helpcenter#170]
Hi Akeneo Team,

Please guide me steps to create/update an attribute (text field) that don't want to belongs to common level.

Steps i have followed:- i have created a configurable product as well as created simple products and did the association using pim akeneo its working fine.

Please find the screen shots:-
![product model every day pouch edit](https://user-images.githubusercontent.com/23648470/35046239-67b0f3fc-fbbc-11e7-9272-c3a931bab770.png)
![product 20939 edit](https://user-images.githubusercontent.com/23648470/35046240-683e54c2-fbbc-11e7-8d61-eff4b14b15dc.png)
![product 20938 edit](https://user-images.githubusercontent.com/23648470/35046241-68860b28-fbbc-11e7-8ce1-1ebb2e7111c9.png)

but some attributes like name, cost price, Selling Price,  MRP  these values **unable** to update at simple products level. message displays like: "**This attribute can be updated on the common attributes.**"

i need to update/change those attributes values.

Please suggest me

thanks

**Comment by Delphineray** [comment]
Hello @NagarajuKasa,

The definition of which attributes are common or managed at the product level is defined in the family variant (tab variant in the family settings). By default all the attributes of the family are common attributes (except the product identifier and the attributes with the unique property at the product level)
You can refer to our following article on our helpcenter: https://help.akeneo.com/articles/manage-your-families.html#manage-family-variants

Regards,
Delphine

**Comment by NagarajuKasa** [comment]
thanks for your help @Delphineray  its working fine.

**Comment by Delphineray** [comment]
Thanks for your feedback!
