### ISSUE TITLE
Warning :- parent: Property "parent" cannot be modified,?

### ISSUE THREAD

**Issue by NagarajuKasa** [akeneo/pim-helpcenter#171]
Hi Team,

i am able to import configurable product via pim akeneo connector. but while i am trying to associate the simple products to configurable product (product model ) i am getting an error called **"Property "parent" cannot be modified"** could you please help me or guide me how to fix this.

Please find the screen shot:-

thanks
![import executions details](https://user-images.githubusercontent.com/23648470/35085664-b2faa4f0-fc4f-11e7-85e4-6b2952eae4d0.png)
![products](https://user-images.githubusercontent.com/23648470/35085836-57defd04-fc50-11e7-930f-0d4aa6dedaed.png)

simple products csv:-
![screenshot from 2018-01-18 13-03-25](https://user-images.githubusercontent.com/23648470/35085786-2bc8e7ca-fc50-11e7-93b0-120da0a930b9.png)

**Comment by LaureBro** [comment]
Hello @NagarajuKasa, 

Did you manage to update your products?
Kind regards, 
Laure

PS : like mentioned in the other issue, please post your questions/issues on our Community Dev repo.

**Comment by LaureBro** [comment]
Without any feedback from you since the 9th of February, I'm closing this issue.
If your problem remains, please post it on our Community repo : https://github.com/akeneo/pim-community-dev/issues
