### ISSUE TITLE
how to import image using csv?

### ISSUE THREAD

**Issue by NagarajuKasa** [akeneo/pim-helpcenter#172]
Hi Akeneo Team,

I would like to import an image for the simple and configurable products using csv. 
but where i have to keep the image files (directory)? what exact procedure need to follow to import an image? please suggest me.

thanks

**Comment by LaureBro** [comment]
Hello @NagarajuKasa , 

This repository is dedicated to Akeneo Help Center, if you need assistance using the PIM, you can go on our repository: https://github.com/akeneo/pim-community-dev/issues.

Kind regards, 
Laure

**Comment by LaureBro** [comment]
Dear @NagarajuKasa ,

Without any feedback from you since the 9th of February, I'm closing this issue.
If your problem remains, please post it on our Community repo : https://github.com/akeneo/pim-community-dev/issues
