### ISSUE TITLE
Search gives unexpected results

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-helpcenter#262]
On the frontpage https://help.akeneo.com/ I can read the welcome message `For instance, try "What is a family?", "Projects" or "How do I set permissions?"`.

But when I type one of the example in the search box (f. ex. `What is a family?`) I get to an unexpected result (-> `What happens when the system integrator changes?`). When I instead directly click on the link I get to the expected result (-> `What is a family?`)

**Comment by NolwennP** [comment]
Hi @Hocdoc,
We are currently doing an update on our website. In the meantime, the search is a little bit broken.
I'll give some update whenever everything is back to normal.

**Comment by LaureBro** [comment]
Hello @Hocdoc, this seems to be fixed :)
![screenshot 2018-11-21 at 13 51 54](https://user-images.githubusercontent.com/13367999/48842464-a7259180-ed94-11e8-9132-fc1966b7f8fb.png)

Kind regards, 
Laure

**Comment by Hocdoc** [comment]
Yes it works now, thanks!
