### ISSUE TITLE
Deadlink assets

### ISSUE THREAD

**Issue by Doodoune** [akeneo/pim-helpcenter#502]
https://help.akeneo.com/pim/serenity/articles/what-is-an-attribute.html

Link "What is an asset?" link to https://help.akeneo.com/pim/serenity/articles/what-is-an-asset.html (ERROR404)

![screenshot_5](https://user-images.githubusercontent.com/34027529/75456962-7fe84780-597b-11ea-999c-cd796d22b277.png)

**Comment by Doodoune** [comment]
Another one in https://help.akeneo.com/pim/serenity/articles/manage-your-account.html

Link to "asset grid" refers to https://help.akeneo.com/pim/serenity/articles/work-with-assets.html#view-the-assets-list (ERROR 404)

![screenshot_6](https://user-images.githubusercontent.com/34027529/75457488-d30eca00-597c-11ea-8679-331364dfc6a2.png)

**Comment by Doodoune** [comment]
Another one in https://help.akeneo.com/pim/serenity/articles/work-on-your-assets.html#follow-the-assets-completeness

Link to "https://help.akeneo.com/pim/serenity/articles/manage-assets.html" (ERROR 404)

![screenshot_7](https://user-images.githubusercontent.com/34027529/75457860-4c0e2180-597d-11ea-89e0-dedba1f81bc9.png)

**Comment by Doodoune** [comment]
Another one in https://help.akeneo.com/pim/serenity/articles/manage-your-users.html#deal-with-the-user-permissions

Link to "Set rights on your assets" refers to https://help.akeneo.com/pim/serenity/articles/access-rights-on-assets.html (ERROR 404)

![screenshot_8](https://user-images.githubusercontent.com/34027529/75458244-d6ef1c00-597d-11ea-9e88-39733945ac40.png)

**Comment by Doodoune** [comment]
Another one in https://help.akeneo.com/pim/serenity/articles/manage-your-users.html#deal-with-the-user-permissions

Link to "Set rights on your assets" refers to https://help.akeneo.com/pim/serenity/articles/access-rights-on-assets.html (ERROR 404)

![screenshot_8](https://user-images.githubusercontent.com/34027529/75458244-d6ef1c00-597d-11ea-9e88-39733945ac40.png)

**Comment by Doodoune** [comment]
Another one in https://help.akeneo.com/pim/serenity/articles/manage-your-users.html#deal-with-the-user-permissions

Link to "Set rights on your assets" refers to https://help.akeneo.com/pim/serenity/articles/access-rights-on-assets.html (ERROR 404)

![screenshot_8](https://user-images.githubusercontent.com/34027529/75458244-d6ef1c00-597d-11ea-9e88-39733945ac40.png)

**Comment by Doodoune** [comment]
Another one in https://help.akeneo.com/pim/serenity/articles/full-manual-pam-migration.html#to-display-the-assets-linked-to-a-product

Link "Working with assets in an asset collection atribute." (typo 'attribute') refers to https://help.akeneo.com/pim/serenity/articles/work-with-assets-in-an-asset-collection-attribute-ee-only.html

![screenshot_9](https://user-images.githubusercontent.com/34027529/75462246-3fd99280-5984-11ea-9776-bb101c114340.png)

**Comment by morganen** [comment]
Done! Thanks a lot.
